---
title: "write.hack"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###<span style="color: blue;">March 16: Updated schedule and projects pages</span>

<span style="color: blue;">For complete information on the updates, click [here](https://smartjw.github.io/collaborative_writing/updateonline.html)
</span>


In this writing course, we explore the writing process through cooperation, collaboration, remixing, and sharing of ideas.  We will also discuss and reflect on the ownership of ideas, the ethics of sharing, and the power structures that underlie our traditions and practices in writing. Readings for the course will include academic works on the writing process and revision.  Additionally, we will examine issues related to ownership, writing, and collaboration through reading texts by Cory Doctorow, Steven Levy, Lawrence Lessig, and others. Writing assignments will incorporate online and collaborative tasks, as well as individual writing projects. 
 
##How to use this site
* The [schedule](https://smartjw.github.io/collaborative_writing/schedule.html) page gives a day-by-day list of the readings you should complete, the major assignments, and what we will be discussing in class meetings. This page is updated frequently. 
* The [projects](https://smartjw.github.io/collaborative_writing/resources.html) page provides detailed instructions for each of the major writing assignments.  
* The [connections](https://smartjw.github.io/collaborative_writing/connections.html) page links to other resources (e.g., library archives, makerspaces) that you will need to complete some of the major assignments.  
* The [home](https://smartjw.github.io/collaborative_writing/index.html) page, once you've read it once, is pretty useless.  


##General Iinformation

Professor [Jon Smart, PhD](https://github.com/smartjw)	
Office Hours: Wednesdays 11-12 & by appt.			
Office: Tribble Hall C-113			
Email: [smartjw@wfu.edu](mailto:smartjw@wfu.edu) 		
Phone: 758-8633  		
Course Information & Policies: [Click Here](https://smartjw.github.io/collaborative_writing/information.html)



