---
title: "Information"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
This website is the primary platform for sharing information with the class.  Additionally, look for emails in your WFU account and some documents and activities in Google Drive.  Final versions of major writing assignments will be submitted through Sakai.  

#General Information:

Professor [Jon Smart, PhD](https://github.com/smartjw)	
Office Hours: Wednesdays 11-12 & by appt.			
Office: Tribble Hall C-113			
Email: [smartjw@wfu.edu](mailto:smartjw@wfu.edu)
Phone: 758-8633


**Required texts for the course:** 
Graff, G. & Birkenstein, C. (2018) *"They Say / I Say": The Moves That Matter in Academic Writing* (4th ed). Norton. 

In addition to the required texts, please bring writing materials and your laptop to class each day. 			

**The goals of the course are:**
1. To foster critical thinking skills by recognizing how language use both enables and constrains public discourse, and by learning how to use language effectively and ethically.
2. To develop understandings of style, genre, and other conventions that are appropriate to audience, context, and purpose.
3. To practice writing as a self-reflexive process including invention, drafting, peer response, and revision.
4. To participate in academic conversations by analyzing, incorporating, engaging, evaluating and/or responding to the works of others.

These goals will be met through class discussions and individual writing projects (see descriptions below), along with in-class writing activities, homework assignments, collaborative tasks, and weekly readings. 

**Grading and assessment**
Grading in the course is based on a few factors.  Of primary importance is your work on the four major writing projects. These projects involve invention, drafting, collaboration, and revising.  Being willing to work with your classmates and open to learning from them is critical to be successful at each of these writing projects.  In addition to the writing projects, there will be frequent smaller tasks (usually one a week) that will help apply ideas from readings to writing/academic research.  

#Course policies

**Group writing and meetings**
Writing 111 is a four-hour course, but meets weekly for three hours.  The fourth hour is for collaborating on your writing with your peers (in a writing group) and with me.  For each major paper, you and your writing group will meet with me for an hour-long workshop outside of regular class meeting times. 

**Attendance** 
Participating in the class is very important.  This course is based on collaboration and discussion.  I expect students to be in class, prepared for the day, and engaged with the materials and tasks each day. As a result, if you miss more than two classes, your final grade for the course will be lowered.  Additionally, it is important to start class promptly on time; please be seated and ready to begin class as soon as the period begins.  I will, likewise, endeavor to end class on time each day.  

**Accommodation** 
If you have a disability that may require an accommodation for taking this course, then please contact the Learning Assistance Center (336.758.5929) within the first two weeks of the semester.
 
**Academic Honesty and Plagiarism**  
As members of the campus community, it is important for students to understand the practices and expectations of the community.  A major violation of these expectations, in terms of academic writing, is plagiarism.  In class, we will discuss and practice strategies to make sure your writing properly cites sources and generally reflects the best practices of academic writing.  All students, both in this course and in all Wake Forest courses are expected to conform to the guidelines described in [Academic Writing at Wake Forest](http://college.wfu.edu/english/course-information/academic-writing/) and the [Honor System](http://deanofstudents.wfu.edu/conduct/honor/) at Wake Forest. 

**Diversity Statement**
Wake Forest University is a community that seeks to enhance knowledge, opportunities and services that result in a richer and fuller life for those who experience our campus community.  This commitment is strengthened with the recognition by the University that diversity constitutes a broad range of attributes beyond race and gender. The University welcomes and celebrates diversity and inclusion in its decisions regarding recruitment, employment, promotion, transfer, reduction in force, termination, compensation and training and development.

The true value of diversity cannot be measured exclusively by the number of individuals who are unique on our campus, but must also include the welcomed interactions, lively discussions and shared experiences found in the Wake Forest University community.  It is an environment that is conducive to embracing, nurturing and fostering that broad definition of diversity while giving life to our motto, “Pro Humanitate” (i.e., for humanity).

**Phones**
No cellphone use in class.  Please turn them off and put them away.  Do not use your phone secretively or leave it on your desk.   Because participation in class is important, avoid using any messaging or social media during the class (including on your laptop).   In addition, as we will often use laptops in class, please refrain from non-class related activities during class.  

**Food & Drink**
Drinks are permitted in class.  Food, barring special exceptions, is not.  


#Course schedule

Unit 1: Remixing & repurposing

* **January 17:** Read Walter's (2013) essay [Sparks will fly](https://aeon.co/essays/consumer-culture-is-dead-long-live-creators) and identify what are the main issues he addresses in the text. How do these relate to the themes of this course? In class on Friday, we'll talk about these ideas and reflect on what creator culture might look like.  
* **January 22:** Read the first chapter of Levy's book [Hackers: Heroes of the computer revolution](http://www.gutenberg.org/ebooks/729). 
* **January 24:** Read the second chapter of Levy's book [Hackers: Heroes of the computer revolution](http://www.gutenberg.org/ebooks/729). Today we'll work on defining the "hacker ethic" and exploring how this could apply to ideas like writing and research.  
* **January 29:** This week, we're going to switch gears a bit (temporarily) and talk about writing specifically. Today we'll be talking about writing a summary of a text and responding it to it.  Specifically, you'll be asked to write a summary and response to the excerpt we read from Levy's book.  
* **February 1**  For this class, read Straub's (1999) chapter [Responding - Really Responding - to Other Students' Writing](https://github.com/smartjw/collaborative_writing/blob/master/docs/straub_responding.pdf). We'll continue working on our summary and response work and discuss how writing groups work.  
* **February 5** Today we will be meeting in ZSR 624 (Special Collections classroom) to learn about the digital collections and archives at Wake Forest.  This will be integral to generate ideas for the second unit.  




