---
title: "Repurpose/Remix"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Overview of the project 

For the second writing project of the course, you will create a physical object using resources available in the WFU Wakerspace (or comparable product).  This should be using a technique or method of making that you have *not* done before. The object should incorporate and repurpose language from the ZSR archives to express a new, contemporary idea or to comment on an old idea. 

The *writing* component of the project consists of two tasks: a project report and a reflection.  

##Formatting

Both the project report and the reflection must adhere to APA style guidelines and should include in-text citations and references where appropriate (make sure to cite sources in-text and include the text on your reference page).  

##Content and organization

**The project report** is a two+ page technical document that illustrates the process of creating something from invention to final development.  The report should be organized following the process you used to invent, design, and produce the object.  In this report, discuss where you found the original archival message(s) and your rationale for choosing them. Describe the original source, as well as how it is stored (e.g., is it part of a larger collection?) and accessed (e.g., digital, print, in Special Collections). The report should also provide the reader with an overview of the process of designing and producing your final object. What steps did you follow? What information did you have to gather? 

**The reflection essay** is a three+ page document that explores your rationale and experience in repurposing and/or remixing language and ideas from  archival resources and turning them into something new. In this task, reflect on how ideas of invention, iteration, read/write culture, and remixing play a role in creation and design. For this task, you should refer to course readings (or other, related readings) as part of the reflection.  

##Steps to the project

* The initial draft of your project report and reflective essay should be shared via Google Docs by February 28th. You and your writing group will need to schedule a meeting with me to go over your drafts. The final version of both writing tasks will be due on March 17th via Sakai.  

* The final physical object should be completed by Friday, February 28th.  We will share them in class on March 4th.  
