---
title: "Writing Projects"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Major assignments (including prompts, due dates, and formatting guidelines) will be listed here for each unit.

###<span style="color: blue;">Update: Projects 2 & 3 have revised information and due dates to reflect out change to an online-only course.
</span>


##Project 1: Summary & Response

###Overview of the project 

For the first writing project of the course, you will write a brief (three pages or longer) essay that includes a summary and response to the **hacker ethic** proposed in Levy's (1984) book *Hackers: Heroes of the Computer Revolution*.  

###Formatting

The paper must adhere to APA style guidelines and should include in-text citations and references where appropriate (make sure to cite Levy in-text and include the text on your reference page).  Make sure to refer to the original author(s) and the title of the article in the beginning of your summary.The summary and response should be subsections of a single paper with a single title and reference page.  

###Content and organization

The first portion of your essay should be a summary that details the main ideas and key supporting details of the original text. 
The second portion of the essay should be a personal response that reflects on the original text.  Your response should include a thesis statement that addresses one of three types of responses:

1.	How your personal experience(s) relate to the original text.
2.	How the ideas from the text can be applied to a comparable situation.
3.	Whether you agree or disagree with the text and why.  

###Steps to the project

Share your draft with your writing group by Friday January 31st. You and your writing group will need to schedule a meeting with me to go over your drafts.  The final draft is due February 14th via Sakai.  

##Project 2: Repurpose

###Overview of the project 

For the second writing project of the course, you will create a physical object using resources available in the [WFU Wakerspace](https://wakerspace.wfu.edu/) (or comparable object).  This should be using a technique or method of making that you have *not* done before. The object should incorporate and repurpose language or imagery or similar from the [ZSR special collections](https://zsr.wfu.edu/special/) or [digital archives](https://zsr.wfu.edu/special/collections/digital/) to express a new, contemporary idea or to comment on an old idea. 

For example, you might find language in an archived edition of the Old Gold & Black or the Howler that reflects a controversial attitude.  You may repurpose the quote by juxtaposing it with a more modern idea or image in a laser etched wood block.  Or you may find a quote from a historical figure in the archives and repurpose the meaning of the quote and create buttons. Here are some resources that we learned about in our visit to ZSR Special Collections: 

* UNC has a digitized version of Catesby's [Natural History of Carolina, Florida, and the Bahama Islands](https://cdn.lib.unc.edu/dc/catesby/).  There's also a version (in two volumes) at the [Library of Congress](https://www.loc.gov/item/agr02000176/).
* WFU [Howler Yearkbooks](https://lib.digitalnc.org/search?p=Yearbooks+Wake+Forest+University&sf=year&so=a) and the [Old Gold & Black](http://wakespace.lib.wfu.edu/handle/10339/48)
* To access digital versions of the *Nuremberg Chronicle*, see the links at the bottom of the [Wikipedia entry](https://en.wikipedia.org/wiki/Nuremberg_Chronicle). You can also go directly to the Cambridge University [digitized version](https://cudl.lib.cam.ac.uk/view/PR-INC-00000-A-00007-00002-00888))
* [Finding aid](https://wakespace.lib.wfu.edu/handle/10339/28134) for the Maya Angelou Film and Theater Collection
* [Finding aid](https://wakespace.lib.wfu.edu/handle/10339/27900) for WFU graduate and screenwriter Laurence Stallings.  His [IMDB page](https://www.imdb.com/name/nm0821716/?ref_=fn_al_nm_1) and his [Wikipedia entry](https://en.wikipedia.org/wiki/Laurence_Stallings)

Alongside making the physical object, there are two writing tasks: a **project report** and a **reflective essay.**  

###Formatting

Both the project report and the reflective essay must adhere to APA style guidelines and should include in-text citations and references where appropriate (make sure to cite sources in-text and include the text on your reference page). The report and reflective essay should be subsections of a single paper with a single title and reference page.  

###Content and organization

**The project report** is a two+ page technical document that illustrates the process of creating something from invention to final development.  The report should be organized following the process you used to invent, design, and produce the object.  In this report, discuss where you found the original archival message(s) and your rationale for choosing them. Describe the original source, as well as how it is stored (e.g., is it part of a larger collection?) and accessed (e.g., digital, print, in Special Collections). The report should also provide the reader with an overview of the process of designing and producing your final object. What steps did you follow? What information did you have to gather? Make sure to cite the source of your original language/image/etc.

**The reflective essay** is a three+ page document that explores your rationale and experience in repurposing and/or remixing language and ideas from  archival resources and turning them into something new. In this task, reflect on how ideas of invention, iteration, read/write culture, and remixing play a role in creation and design. For this task, you should refer to course readings (or other, related readings) as part of the reflection.  

###Steps to the project

* The initial draft of your project report and reflective essay should be shared via Google Docs by February 28th. You and your writing group will need to schedule a meeting with me to go over your drafts. The final version of both writing tasks will be <span style="color: blue;">due on March 25th</span> via Sakai. 

If you would like to [make an appointment](https://calendar.google.com/calendar/selfsched?sstoken=UUc1WHljZHl2cHFRfGRlZmF1bHR8MDg4ZmI1NzkxZjMwNWUyYWMzMTI1MjgzMDlkNDBiYzk) with me for an individual conference, you are welcome to, but this is optional.  

* The final physical object should be completed by Friday, February 28th.  We will share them in class on March 6th.  

##Project 3: Synthesizing ideas

*Note: this project was originally planned as a collaborative wiki. However, given the campus-wide switch to remote learning, the assignment is now for each student to individually author a guide using collaborative sources via Zotero.*  

###Overview of the project 

For this writing project, you will write a guide that describes how to incorporate and make use of others’ texts in academic writing.  To that end, you will need to choose a specific topic from the list below.  

1.	Incorporating information effectively in academic writing
2.	Citing and incorporating information in the humanities
3.	Citing and incorporatinginformation in the social sciences
4.	Citing and incorporatinginformation in STEM fields
5.	Restating and remixing ideas in academic writing
6.	Copyright issues and plagiarism in academic writing

To choose your topic, please complete the following ranking survey by March 25.  Dr Smart will send you an email with your topic based on the survey results:

https://forms.gle/yJ411nRjoDo3Ht91A

###Formatting

This five+ page paper should be double-spaced and must adhere to APA style guidelines and should include in-text citations and references where appropriate.  The paper should incorporate at least five sources of information; all sources should be either assigned course readings or peer-reviewed academic essays or academic books (at least one source should be one of the latter two).  

###Content and organization

Before beginning writing the paper, use ZSR's online databases to research your topic. Make sure you upload at least two new sources (peer-reviewed research articles or academic e-books) to our shared Zotero library.  

The paper should be organized into two sections: 

* *A literature review* (3 pages) summarizing and [synthesizing](https://users.drew.edu/sjamieso/synthesis.html) the current research and/or best practices related to your topic. 

* *An instructional section* (2 pages) that explains steps/techniques related to your topic and uses appropriate examples to illustrate those techniques. To create authentic examples, you may find a collection of essays like [MiCUSP](https://micusp.elicorpora.info/) to be helpful.  

###Steps to the project

1. March 25: Complete the topic [survey](https://forms.gle/yJ411nRjoDo3Ht91A)
2. March 25: Install Zotero and join the class Zotero group.
3. April 1: Add two (or more) peer-reviewed articles/e-books to the Zotero group library.
4. April 10: Upload your draft to the appropriate subfolder on the shared Google Drive and make an individual [appointment](https://calendar.google.com/calendar/selfsched?sstoken=UUc1WHljZHl2cHFRfGRlZmF1bHR8MDg4ZmI1NzkxZjMwNWUyYWMzMTI1MjgzMDlkNDBiYzk) with me.
5. April 15: Comment on your writing group's drafts and send them an email.
6. April 22: Submit your final draft via Sakai.  

##Project 4: Original Plagiarism

###Overview of the project 

For the final writing project of the semester, complete a writing task based on "An original plagiarism" from the [Remix] chapter of Harris' (2017) book Rewriting. For the topic, write about something you've read or discussed or thought about in this course.  It could be any of the following: 
* Read/Write Culture
* Hacking
* Self-expression/copyright
* Remixing

Or, you could write about a topic relevant to our bizarre experiences this semester (COVID-19, isolation, social distancing, remote learning, etc.). The primary constraints for the assignment is that it should remix, appropriate, or tweak language from several other texts.  

###Content and organization

This is a two-part task.  The first part is the "original plagiarism", which should be 400-500 words. This section should contain *mostly* language from other people that you are co-opting (i.e., stealing) as your own. Lethem's (2007) [The Ecstasy of Influence](https://archive.harpers.org/2007/02/pdf/HarpersMagazine-2007-02-0081387.pdf?AWSAccessKeyId=AKIAUXG2GD7CYHBPPE7E&Expires=1583437546&Signature=ZNEVEZGG60LUHfGDZYUEL8woeFs%3D) is an extended example of this type of writing.  In the document, be sure to include a "key" to indicate your sources (i.e., which sentences/phrases came from which source).  The key can be footnotes, color-coded fonts, or similar.  

The second part of the essay is a brief reflection on your aims as a writer in composing this "plagiarized" essay. Refer to related readings (e.g., Harris, 2007; Lessig, 2008) as necessary. This should be approximately the same length as the first part.   

###Steps to the project

* Optional: Upload your first draft to Google Drive by April 29
* Optional: Read and comment on your peers' drafts once they are uploaded.  
* Submit the final draft via Sakai by May 6




