---
title: "Course Schedule"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


General course information and and policies can be found [here](https://smartjw.github.io/collaborative_writing/information.html)

Presentation slide decks and other materials can be accessed [here](https://drive.google.com/drive/folders/151MO4X588GUHBqkvbS0s_QrZrseMGZqN)

#Unit 1: Rephrase & respond			

The writing project for this unit is Project 1: Summary & Response.  Read about the project [here](https://smartjw.github.io/collaborative_writing/summaryresponse.html).  

###January 15: 

Today we'll discuss essential first day information (introductions, syllabus, grading, etc.).  Slides [here](https://drive.google.com/a/wfu.edu/file/d/1qpO8FcCvipcwdgLsxCa9IT3wuFziUsHq/view?usp=sharing).

###January 17: 

Read Lake's (2013) essay [Sparks will fly](https://aeon.co/essays/consumer-culture-is-dead-long-live-creators) and identify what are the main issues he addresses in the text. How do these relate to the themes of this course? In class on Friday, we'll talk about these ideas and reflect on what creator culture might look like.  Slides [here](https://drive.google.com/a/wfu.edu/file/d/1M_aSPPVRVLMOTUDyxL_f0mkv8_M2b_Wx/view?usp=sharing).

###January 22: 

Read the first chapter of Levy's (1984) book [Hackers: Heroes of the computer revolution](http://www.gutenberg.org/ebooks/729). We'll continue working on our summary and response work and discuss how writing groups work. Slides [here](https://drive.google.com/open?id=1728CFUrKEXlV0FGvSld_j4fv_51_jn9E)



*note: if you find the format of the Gutenburg.org version hard to read, a PDF is available via Sakai (under Resources).*

###January 24: 

Read the second chapter of [Hackers](http://www.gutenberg.org/ebooks/729). Today we'll work on defining the "hacker ethic" and exploring how this could apply to ideas like writing and research.Today we'll be talking about writing a summary of a text and responding it to it.  Specifically, you'll be asked to write a [summary and response](https://smartjw.github.io/collaborative_writing/summaryresponse.html) to the excerpt we read from Levy's book. Slides [here](https://drive.google.com/a/wfu.edu/file/d/1eNf2yF-WErumMiJv54hYizwefd1pkZX3/view?usp=sharing). 

###January 29: 

This week, we're going to switch gears a bit (temporarily) and talk about writing specifically. 

###January 31:  

For this class, read Straub's (1999) chapter [Responding - really responding - to other students' writing](https://github.com/smartjw/collaborative_writing/blob/master/docs/straub_responding.pdf).   

#Unit 2: Remix & repurpose

For this unit, we'll be reading about remixing and repurposing (and some of the legal issues and cultural values related to these issues).  The [writing project](https://smartjw.github.io/collaborative_writing/repurpose.html) for this unit is to explore (and reflect on) the proces of repurposing language and media from our library archives to create something new using the WFU Wakerspace.  As part of the assignment, you will will create an object and write an extended reflection on the process and your goals. 

###February 5: 

Today we will be meeting in ZSR 624 (Special Collections classroom) to learn about the digital collections and archives at Wake Forest.  This will be integral to generate ideas for the second unit. 

To prepare for this week's class, please read the following two excerpts from to Lawrence Lessig's (2008) book *[Remix](https://archive.org/details/LawrenceLessigRemix/mode/2up)* (click here for the [PDF](https://ia802306.us.archive.org/24/items/LawrenceLessigRemix/Remix-o.pdf) Version):

* Introduction (pp. 1-19)
* The first few sections of Chapter Four: RW, Revived (pp. 51-68)

*notes: If you are interested in the video Lessig mentions in the first chapter you can see it [here](https://youtu.be/N1KfJHFWlhQ).* 

Some of the resources discussed in class today: 
 
* UNC has a digitized version of Catesby's [Natural History of Carolina, Florida, and the Bahama Islands](https://cdn.lib.unc.edu/dc/catesby/).  There's also a version (in two volumes) at the [Library of Congress](https://www.loc.gov/item/agr02000176/).

* WFU [Howler Yearkbooks](https://lib.digitalnc.org/search?p=Yearbooks+Wake+Forest+University&sf=year&so=a) and the [Old Gold & Black](http://wakespace.lib.wfu.edu/handle/10339/48)

* To access digital versions of the *Nuremberg Chronicle*, see the links at the bottom of the [Wikipedia entry](https://en.wikipedia.org/wiki/Nuremberg_Chronicle). You can also go directly to the Cambridge University [digitized version](https://cudl.lib.cam.ac.uk/view/PR-INC-00000-A-00007-00002-00888))

* [Finding aid](https://wakespace.lib.wfu.edu/handle/10339/28134) for the Maya Angelou Film and Theater Collection

* [Finding aid](https://wakespace.lib.wfu.edu/handle/10339/27900) for WFU graduate and screenwriter Laurence Stallings.  His [IMDB page](https://www.imdb.com/name/nm0821716/?ref_=fn_al_nm_1) and his [Wikipedia entry](https://en.wikipedia.org/wiki/Laurence_Stallings)

###February 7: 

We will be discussing Lessig's ideas of read-only and read/write culture in class (with a focus on the latter).  We'll also be talking about how this connects to our next writing assignment.
Slides [here](https://drive.google.com/open?id=1t0apAtGViG3Bk2aXL_IDza-j_aoSOJNFtPtSY02hCyI).

###Feburary 12: 

Today we will be meeting in the Wakerspace [on campus](https://map.concept3d.com/?id=492#!m/388915) during the regular class meeting time.  This will be an introduction to the space and will give you ideas for how you might approach your remix/repurpose project. The [Wakerspace](https://wakerspace.wfu.edu/) is a variation on what are traditionally called [Makerspaces](https://en.wikipedia.org/wiki/Hackerspace) (or Hackerspaces) and has a wide-range of tools and hands-on resources for creation and design.  Before class, please watch Robin Hooker's (2018) [TED talk](https://youtu.be/9lSZgCaMS20) on "A makerspace for everyone"

*notes: If you are interested in signing up for specific Wakerspace workshops, you can find them [here](https://pdc.wfu.edu/?q=wakerspace&opento&types). You may also be interested in learning about the non-profit makerspace downtown, [Mixxer](https://wsmixxer.org/).*



###February 14: 


On Friday, we will bring these ideas together (ZSR archives, Makerspace, and remix culture).  To prepare for this class discussion, please complete the following

* Read the remainder of [Lessig's](https://archive.org/details/LawrenceLessigRemix/mode/2up) chapter 4 (pp. 68-83).  

* Watch Cory Doctorow's Stanford [lecture](https://youtu.be/tveAm35gVF4) on Copyright and Remix Culture

*notes: You can find a playlist of Jonathan McIntosh's remix videos [here](https://www.youtube.com/playlist?list=PLBA459CB6C73D3B9A).*


###February 19 & 21: 

In this week's class, we're going to take a slight detour (content-wise) and read a bit of fiction and a response to the story. 

For **Wednesday**, please read the short story [Affordances](https://slate.com/technology/2019/10/affordances-cory-doctorow-sf-story-algorithmic-bias-facial-recognition.html) by [Cory Doctorow](https://en.wikipedia.org/wiki/Cory_Doctorow). The story explores connections between the control of information, personal technology, and identity.  If you prefer to listen to the story, an mp3 version is available [here](https://archive.org/download/Cory_Doctorow_Podcast_314/Cory_Doctorow_Podcast_314_-Affordances.mp3) (right-click to download the audio).

On **Friday**, we will read and discuss a [response](https://slate.com/technology/2019/10/cory-doctorow-affordances-response-ai.html) to the story by [Nettrice Gaskins](https://en.wikipedia.org/wiki/Nettrice_Gaskins).  

###February 26

This week, we're going to start a discussion on the intersection of writing and ideas we've been discussing so far (i.e., hacking and remixing).  To that end, we'll start by reading the first part of *They Say, I Say* (Graff & Birkenstein, 2018).  Please read the introduction and chapters one through three (i.e., pp. 1-52).  Also, make sure you are working on the drafts of your [project two](https://smartjw.github.io/collaborative_writing/resources.html#project_2:_repurpose_and_remix) essays, as the draft is due on February 28th. Also, make sure you and your writing group have signed up for a workshop time on my [appointment calendar](https://calendar.google.com/calendar/selfsched?sstoken=UUc1WHljZHl2cHFRfGRlZmF1bHR8MDg4ZmI1NzkxZjMwNWUyYWMzMTI1MjgzMDlkNDBiYzk).  

Today we'll also discuss the Smithsonian's recent ["release"](https://www.smithsonianmag.com/smithsonian-institution/smithsonian-releases-28-million-images-public-domain-180974263/) of [2.8 million images](http://collections.si.edu/search/) into the public doman and their efforts to encourage [remixes](https://learninglab.si.edu/cabinet/file/4e0ad443-7b49-420f-8853-5e3f0d2e3f04/how-to-make-a-collagasaurus.pdf) of their archived materials.  

###February 28

*Please add your draft of [project two](https://smartjw.github.io/collaborative_writing/resources.html#project_2:_repurpose_and_remix) to the appropriate folder on our shared Google drive.  Creating the draft as a Google Doc (instead of uploading a Word document) can help your writing group comment more easily on the document.*

For today's class, please read through Part Two of *They Say, I Say* (pp. 53-100).  

###March 4

For today's class [Molly Keener](https://zsr.wfu.edu/directory/molly-keener/) will be coming to talk to our class about issues related to copyright, intellectual property, and other issues/questions you may have. To prepare for today's class, read Broussard's (2007) article on [The Copyleft Movement: Creative Commons Licensing](https://github.com/smartjw/collaborative_writing/blob/master/docs/broussard_copyleft_movement.pdf).

Also, read this short excerpt from Doctorow's (2014) book [Information Doesn't Want to be Free: Laws for the Internet Age](https://github.com/smartjw/collaborative_writing/blob/master/docs/doctorow_excerpt_idwtbfree.pdf).

Handouts from Molly Keener's class discussion are [here](https://github.com/smartjw/collaborative_writing/blob/master/docs/CC-License-Handout.pdf) and [here](https://github.com/smartjw/collaborative_writing/blob/master/docs/copyright_the_basics.pdf). The original general information flyer on Creative Commons is available on the organization's [website](https://wiki.creativecommons.org/images/6/62/Creativecommons-informational-flyer_eng.pdf).


###March 6

We will be discussing Part Three of *They Say, I Say*. We will also be sharing our finished, physical products; please bring your object to class and be prepared to introduce the class to your work, method, and rationale.  

[Click here](https://smartjw.github.io/collaborative_writing/studentproducts.html) to explore the works from today's class. 


#Unit 3: Collaborate

The writing project for this unit will be to create a collaborative wiki with your classmates.  You can read more about the Project #3 details [here](https://smartjw.github.io/collaborative_writing/resources.html).

###March 18

For this class period, we will begin our discussion of our third writing project. For this unit we will read and discuss ideas related to collaboration in writing (and other types of collaboration). To move from Unit 2 to Unit 3, in today's class, we're talking about how ideas of remixing and hacking are related to collaboration in academic writing specifically. 

Before class, please read (and take notes) the chapter [Remixing](https://github.com/smartjw/collaborative_writing/blob/master/docs/harris_remixing.pdf) from the Harris' (2017) book *Rewriting: How to do things with texts*.

*note: You can read Lethem's (2007) [The Ecstasy of Influence](https://archive.harpers.org/2007/02/pdf/HarpersMagazine-2007-02-0081387.pdf?AWSAccessKeyId=AKIAUXG2GD7CYHBPPE7E&Expires=1583437546&Signature=ZNEVEZGG60LUHfGDZYUEL8woeFs%3D) here if interested.*

###March 20

Project 3 is a collaborative wiki that the class will construct together. Specifically, we are creating [a guide to citing](https://sites.google.com/a/wfu.edu/citing_sources_wiki/) (and making use of) others' texts and ideas in academic writing. You and a partner will be assigned a particular subpage to develop and edit.  To prepare for our initial discussion on this topic, please read Stedman's (2011) [Annoying Ways People Use Sources](http://writingspaces.org/sites/default/files/stedman--annoying-ways.pdf) from the open textbook *[Writing Spaces](http://writingspaces.org/)*.

###March 25

In today' class, librarian [Meghan Webb](https://zsr.wfu.edu/directory/meghan-webb/) will be showing us how to use Zotero for class collaboration. Before class, make sure you have installed Zotero and have it running on your computer.  Wake has a [guide](https://guides.zsr.wfu.edu/zotero/install) for installing Zotero. Also, make sure you have Microsoft Word with Zotero working. You can get Word as part of the MS Office 365 program through WFU's [software download page](https://software.wfu.edu/). Zotero also works in other word processing software (e.g., [Google Docs](https://www.zotero.org/support/google_docs), [Libre Office](https://www.zotero.org/support/libreoffice_writer_plugin_usage), but our workshop will prioritize MS Word. 

###March 27

For today's class, please read Ingall's [Writing “Eyeball To Eyeball”: Building A Successful Collaboration](https://wac.colostate.edu/docs/books/writingspaces2/ingalls--writing-eyeball-to-eyeball.pdf).  

###April 1

We're returning to Levy's *Hackers* to read about one of the most famous collaborations in hacking and repurposing; read chapter twelve [The Woz](https://github.com/smartjw/collaborative_writing/blob/master/docs/hackers_12_woz.pdf) before our class meeting.  






